{
  "_annotation": {
    "cve_id": "CVE-2024-35228",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-35228.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:torchbox:wagtail:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "0D77A4E9-BC7D-52EF-8E01-371B4BF872BC",
                "versionEndExcluding": "6.0.5",
                "versionStartIncluding": "6.0.0",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:torchbox:wagtail:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "F9409E64-F711-5C24-94A7-69DDDB16342C",
                "versionEndExcluding": "6.1.2",
                "versionStartIncluding": "6.1.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}