{
  "_annotation": {
    "cve_id": "CVE-2024-37300",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-37300.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:jupyter:oauthenticator:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "4B63F07A-FE67-52A3-9868-6B6E44D088B0",
                "versionEndExcluding": "16.3.1",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}