{
  "_annotation": {
    "cve_id": "CVE-2024-35225",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-35225.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:jupyter:jupyter_server_proxy:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "55E86A96-DBD6-5AE6-B8AB-3EA7127B8E48",
                "versionEndExcluding": "3.2.4",
                "versionStartIncluding": "3.0.0",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:jupyter:jupyter_server_proxy:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "ACAB31B7-9D9B-55CF-8CA8-3AF681B3E47A",
                "versionEndExcluding": "4.2.0",
                "versionStartIncluding": "4.0.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}