{
  "_annotation": {
    "cve_id": "CVE-2024-29199",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-29199.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:networktocode:nautobot:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "7B3F0359-5599-5FE3-8403-0E9CA211B978",
                "versionEndExcluding": "1.6.16",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:networktocode:nautobot:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "C588C204-2E55-5710-9CB5-7245CCE447AA",
                "versionEndExcluding": "2.1.9",
                "versionStartIncluding": "2.0.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}