{
  "_annotation": {
    "cve_id": "CVE-2024-35198",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-35198.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:pytorch:torchserve:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "D9BA2D92-1B09-5B03-ABD9-2FF80FA2725F",
                "versionEndExcluding": "0.11.0",
                "versionStartIncluding": "0.4.2",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}