{
  "_annotation": {
    "cve_id": "CVE-2024-34707",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-34707.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:networktocode:nautobot:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "23066AF5-1331-5FDC-9E50-9BF54E9402FE",
                "versionEndExcluding": "1.6.22",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:networktocode:nautobot:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "0063B4C9-BAE9-5A04-AC48-599B77BBDF63",
                "versionEndExcluding": "2.2.4",
                "versionStartIncluding": "2.0.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}