{
  "_annotation": {
    "cve_id": "CVE-2024-32474",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-32474.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:functional:sentry:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "40BAC563-B31A-5FC0-AA0B-3122863D0F30",
                "versionEndExcluding": "24.4.1",
                "versionStartIncluding": "24.3.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          },
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:sentry:sentry:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "9FD6BBCA-892E-5BD6-852A-B673CBA1204D",
                "versionEndExcluding": "24.4.1",
                "versionStartIncluding": "24.3.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}