{
  "_annotation": {
    "cve_id": "CVE-2023-6597",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2023/CVE-2023-6597.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "7C9E3962-1E26-5701-BB9F-C997E3E9F4FB",
                "versionEndExcluding": "3.12.3",
                "versionStartIncluding": "3.12.0",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "D2EA6C62-D265-5709-8EDA-35982B091A95",
                "versionEndExcluding": "3.11.9",
                "versionStartIncluding": "3.11.0",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "4E02C8B9-3929-578C-BFE5-083AC25373D7",
                "versionEndExcluding": "3.10.14",
                "versionStartIncluding": "3.10.0",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "91B761FA-92BA-5AE7-A192-90C2B9A7672A",
                "versionEndExcluding": "3.9.19",
                "versionStartIncluding": "3.9.0",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "F983F278-1F6A-5786-98D9-CC68B47656F8",
                "versionEndExcluding": "3.8.19",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}